bersi_blog_homepage:
    path:     /
    defaults: { _controller: BersiBlogBundle:Default:index }

bersi_blog_news:
    path:     /twitch
    defaults: { _controller: BersiBlogBundle:Default:twitch }

bersi_blog_news:
    path:     /{type}/{titre}
    defaults: { _controller: BersiBlogBundle:Default:news }

bersi_blog_contact:
    path:     /contact
    defaults: { _controller: BersiBlogBundle:contact:index }