<?php

namespace Bersi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticlesByCategory(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('a');

        $qb ->join('a.category', 'c')
            ->addSelect('c')
            ->where('a.published = :publish')
            ->setParameter('publish', true)
            ->andWhere($qb->expr()->in('c.name', $categoryNames));

        return $qb->getQuery()->getResult();
    }

}
